expr.c: Fix argument type of expr_write_scope().
There is compile error introduced by the commit 2054d01247.
***
../lib/expr.c:3328:6: error: symbol 'expr_type_check' redeclared with different
type (originally declared at ../include/ovn/expr.h:481) - incompatible argument
4 (different signedness)
Makefile:1971: recipe for target 'lib/expr.lo' failed
***

Fixes: 2054d01247 ("Add expression writeability scopes.")
Acked-by: Ankur Sharma <ankur.sharma@nutanix.com>
Signed-off-by: Han Zhou <hzhou@ovn.org>