ovn-nbctl: Fix 32-bit build with gcc.
ovn/utilities/ovn-nbctl.c: In function 'print_routing_policy':
ovn/utilities/ovn-nbctl.c:3620:23: error: format '%ld' expects argument
    of type 'long int', but argument 3 has type 'int64_t'
                       policy->match, policy->action, next_hop);
                       ^
ovn/utilities/ovn-nbctl.c:3624:23: error: format '%ld' expects argument
    of type 'long int', but argument 3 has type 'int64_t'
                       policy->match, policy->action);
                       ^
ovn/utilities/ovn-nbctl.c: In function 'cmd_ha_ch_grp_list':
ovn/utilities/ovn-nbctl.c:5056:27: error: format '%lu' expects argument
    of type 'long unsigned int', but argument 10 has type 'int64_t'
                           ha_ch->priority);
                           ^
cc1: all warnings being treated as errors
make[2]: *** [ovn/utilities/ovn-nbctl.o] Error 1

https://travis-ci.org/openvswitch/ovs/jobs/521015912

CC: Numan Siddique <nusiddiq@redhat.com>
CC: Mary Manohar <mary.manohar@nutanix.com>
Fixes: 1be1e0e5e0d1 ("ovn: Add generic HA chassis group")
Fixes: a64bb573468f ("Policy-based routing (PBR) in OVN.")
Signed-off-by: Ilya Maximets <i.maximets@samsung.com>
Signed-off-by: Ben Pfaff <blp@ovn.org>