Fix the travis CI compilation error seen for osx job
After the commit [1], travis CI job for osx [2] is failing with the below
error:

*****
In file included from lib/actions.c:25:
./lib/ovn-l7.h:246:9: error: 'ND_OPT_ROUTE_INFO' macro redefined [-Werror,-Wmacro-redefined]
        ^
/usr/include/netinet/icmp6.h:329:9: note: previous definition is here
*****

This patch renames the macro ND_OPT_ROUTE_INFO to ND_OPT_ROUTE_INFO_TYPE as this macro
is used to set the Route Information Option Type.

[1] - 9f7f466af("Add support for Route Info Option in RA - RFC 4191")
[2] - https://travis-ci.org/ovn-org/ovn/jobs/634833728?utm_medium=notification&utm_source=github_status

Fixes- 9f7f466af("Add support for Route Info Option in RA - RFC 4191")
CC: Lorenzo Bianconi <lorenzo.bianconi@redhat.com>
Acked-by: Lorenzo Bianconi <lorenzo.bianconi@redhat.com>
Signed-off-by: Numan Siddique <numans@ovn.org>