binding: Prevent maybe-uninitialized error for queue variable.
The GCC would report that the queue might be uninitialized,
rearrange the code slightly to avoid this error:

In function ‘add_ovs_qos_table_entry’,
    inlined from ‘configure_qos’ at controller/binding.c:419:17,
    inlined from ‘update_qos’ at controller/binding.c:458:17:
controller/binding.c:324:5: error: ‘queue’ may be used uninitialized [-Werror=maybe-uninitialized]
  324 |     ovsrec_queue_set_external_ids(queue, &external_ids);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
controller/binding.c: In function ‘update_qos’:
controller/binding.c:299:26: note: ‘queue’ was declared here
  299 |     struct ovsrec_queue *queue;
      |                          ^~~~~

Fixes: 7d1d111ff213 ("controller: configure qos through ovs qos table and do not run tc directly")
Signed-off-by: Ales Musil <amusil@redhat.com>
Signed-off-by: Dumitru Ceara <dceara@redhat.com>