pinctrl.c: Fix maybe-uninitialized warnings with old GCC versions.
There are warnings with older GCC versions (e.g. 4.9.2):
===
../controller/pinctrl.c: In function ‘ipv6_ra_send’:
../controller/pinctrl.c:2393:13: error: ‘r1’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
             memcpy(&dnssl[i], t1, strlen(t1));
             ^
../controller/pinctrl.c:2383:20: note: ‘r1’ was declared here
         char *t1, *r1;
                    ^
===
This is not a real problem but compile fails because of it. This patch
fixes it by initializing the pointers to NULL, to avoid the warnings
with older GCC.

CC: Lorenzo Bianconi <lorenzo.bianconi@redhat.com>
Fixes: 5a12a940f63a ("Add DNSSL support to OVN")
Acked-by: Numan Siddique <nusiddiq@redhat.com>
Signed-off-by: Han Zhou <hzhou@ovn.org>