ci: Move common build steps into script.
Move common preparation steps into script that can be invoked by both
container builds. This will ensure that any update will be reflected
in both containers, and it reduces the duplication between both
containers. At the same time use the --user argument which avoids
the error below and allows pip to upgrade itself:

ERROR: Cannot uninstall pip 24.0, RECORD file not found.
Hint: The package was installed by debian.

Signed-off-by: Ales Musil <amusil@redhat.com>
Acked-by: Eelco Chaudron <echaudro@redhat.com>
Signed-off-by: Dumitru Ceara <dceara@redhat.com>
(cherry picked from commit cc1d63de213369f3ac096415ad09913455809a81)