ovn-nbctl: Fix using uninitialized direction while removing qos.
GCC 9 complains:
utilities/ovn-nbctl.c: In function 'nbctl_qos_del':
utilities/ovn-nbctl.c:2592:15: error: 'direction' may be used uninitialized in
                               this function [-Werror=maybe-uninitialized]
 2592 |              !strcmp(direction, qos->direction)) {
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If uuid specified along with extra arguments like priority or match,
code might use uninitialized direction for comparison and probably will
crash.  Exit early with error since we're not supporting such command
lines.

CC: Tao YunXiang <taoyunxiang@cmss.chinamobile.com>
Fixes: 3aca9a51c276 ("ovn-nbctl.c: Add an optional way to delete QoS by uuid")
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>
Acked-by: Mark Michelson <mmichels@redhat.com>
Signed-off-by: Numan Siddique <numans@ovn.org>