ovn-controller.c: Fix compile errors.
../controller/ovn-controller.c:3169:51: error: incorrect type in argument 1 (different base types)
../controller/ovn-controller.c:3169:51:    expected struct ovsrec_open_vswitch_table const *ovs_table
../controller/ovn-controller.c:3169:51:    got struct ovsrec_open_vswitch const *cfg
../controller/ovn-controller.c:3215:51: error: incorrect type in argument 1 (different base types)
../controller/ovn-controller.c:3215:51:    expected struct ovsrec_open_vswitch_table const *ovs_table
../controller/ovn-controller.c:3215:51:    got struct ovsrec_open_vswitch const *ovs_cfg

Fixes: b3b75ae4ee53 ("controller: only sample pflow if Collector Set exists")
Fixes: 5b1476709d7c ("controller: only sample flow if Collector Set exists")
Signed-off-by: Han Zhou <hzhou@ovn.org>