rhel: fix logrotate user config option
If rpm is built with libcapng (default), /etc/logrotate.d/ovn
config file user is SEDed in postinstall section with 'ovn ovn'.

If one run logrotate, next error occurs:
```
[root@host ~]# logrotate /etc/logrotate.d/ovn
error: /etc/logrotate.d/ovn:9 unknown user 'ovn'
error: found error in /var/log/ovn/*.log , skipping
```

Replace 'ovn' user with 'openvswitch' to fix the issue.

Signed-off-by: Vladislav Odintsov <odivlad@gmail.com>
Acked-by: Mark Michelson <mmichels@redhat.com>
Signed-off-by: Numan Siddique <numans@ovn.org>
(cherry picked from commit e8800ddd9e919e2ffc9d8c5c9ab27f0a5a6ec2e5)